<?php

$input="SSSXSSMSXMMAXXAXMSSMSSMSXMASXXMXMMXMSXSMXMMSASXMMAMMMMMXSAXMAMASMASASXSXMMMSMAXMSAMXAAXXXAMXSAMSAAMMXASXMXXXXASXMMSMMMMMMMSMMSAMSSSMXSMMXSXM
MXMAMMMSAAMSSSXSMMMMMAMMMXMMXXAAXMAMMAASMSXMASAXSXMAAXAAAMAMXSXXMASMMAMXMAAAXXMASXSSMXAMSXMAMXXSMXXAMXXAXMSMMMMAAAXXAAAXAAAAXSAMMASXAMXXAMAS
XAMAMSAMMMMAAMAAXAAMSAMXSAAXSSSMSSSSMXMAXMAMSMXMAASXMSMMSXMMXAMXMASXMAXAMMXSSMAMSAMXAXMMAMXXXXXMASXMMASXMAAXAASXMASXSSSSMSXSMXAMMMMMMSSMMSAM
SXSASMMSXAMMSMMMSSSMSXSASMSXMAMAAXAAASXMASAMXASMSMMAMSMXXASMMSMXMASMSSMMXSAAMASXMMMASMXMAXMSASXMAMMMSXMASMMSSXSXXXMAMAMMAMAMASMMMMAAAAXAAXXS
MXMXMAXXMXXAAAXAAAAAXAMAMAMMMAMMMMSMMMASXMASMXMAXXSAMMMMSMMAAAAAMMXAAAASAMMSMAMASXMAMMXSSSMXMSAAAXAMXAXAMXMAXMMMXSMAMAMMAMMMXMMAASMSSMSMMMMA
MASMSMMMSMMSXMMXMMMMMMMSMAMSMXSAMXAXXSXMAMXXXXMXMMXMXSAAXXXMMSSXSAMSMSMMASAXMASXMAMMXSAMXAXXXSXMMSSSSSMXSXMASXMMAMSSSXSMMSASXAXSMMXAMXMAAASM
SAXXAMAAAAMAASXMSXAXXSAMSSMMMMSAMXXMASXMAMSXMMSSMMSAASMMSMMSAMMAMMMXAMXSAMMSSXMASMMXAMASXMMMMMAMXXAAAMAMSXMMMMMMAMAXMAMAMSASXSMMASAMXAXXXXMX
MXSSMSMSXSMMXMAAXXAMAMAXAXAASAMXMXMAXXMMAMSAMASAAAMMMSXMAMAMASMXMSMMXMAMXSAMXMSAMASMASAMAAAAASAMXMMMMMSMSASAXAASMMSXMAMAMMAMAXXMAMXSSMSMSSSX
XMAAASMMAMAMSSMMMMSSXSMMMXMMSXXMSMMMSMAMSMSAMSSMMMSMMSXMXMMXXMMXAASMAMAMAMMMMMMXSAMAXMMMAMXSXXAXSMMXSXAAXAMASMMAAXAASASAMXAMMMSMAXAXAAAAAAAM
MASMMMAXAXAMXMASXXAAMMAAXMAMXXXAAAAAAXMXMASAMXMAMXSAMXASAMXMMASMSXMMXMAMMMXMAMSMAMSMSAMXSAMXMMSXAXMMMSMMMMMXMAASMMXXMAMMSSXSAASASASXMMMMMSMA
AMAMXSAMXSSMMXMMMMMSSSSMSAMSASMSMSMSSSXSMAMMXSXXMAXAXSXMXXMASAXXMMSXXSASMSSSMMXAMMSXMXMAXAMXAAMXAMXAMASAAXXXAXMAXSXSMAMXAMASMAMAMAMXMMXMAXAS
SSXSXMXMXSXAMXSAAMXMMAAXAXXMAMAMXMMXAXAXMXSMAMMAMSMSMMMMXSMMMAMXMASAAXAMAAAXMASMXMSAMSMMMAMMMMMAMXXMMAXMMMSMSMSXAXAMMMSMASAXMAXAMXMAXSAMSSMX
XMAMMSAMMSSSMAMMSMAMMSMMMMXMXMMMASXMXMXMAMAMMSMSXASAAAAMMMASMMMAXSMMMSSMMMSMSAXMASMAMAAXSSMXMASMMSSXMMSSMMSAAAXMMMAMAAAMXMMSXMXMXXSAXSMMMSAX
MMSMAXASMXAMMXMAMMAMXAMMXMXSAAASASAXMASAMSSSMSAXMXSMSMXSASAMAASMMMAMXAXMAMXAMMMMXMMAMMMAMMAMXASAAAMASAAMAAMSMSMMXMASMSXSXAMXMMASMMMXXXXAAMMM
XAASMSMMMMAMAAMASXMSMSAMAMMXXSXMASMMMSASAAAAAMMMMAMXMAAXMMAMMMSXAXSMMXXMMAMXAXSASASXSXMASMXMMMSMMMSAMMSSMMMXMAMMAMMSMMXAMXMAMSASAMAXXMSMSMXA
MXMSXAMSXXXMSXSASAXMAXMSASXMMMXMXMMAMAAMMMSMMMXSMXSAMMMMSMXSAMXXSXMASASXSXSXAASAXASAAXSASXSXMAXAAXMXSXMAMSASMMMSASMSASXMSSSMMAAXMMMSAAXAAXMX
SMMXMAMAMSAMXXMASMMMAMXSASMAMAXMAMMSSMXMAMXMXMXMAXMXXSAMXAASXXMAXXSAMMAAMAMMAMMMMMMMMMMMSMXAMSXSMXMMXASAMXMXAAASMSAMXMAMAAAXMMMMXMAXMMMMMMSA
SAMAMSMMAAASXMMAMXAXAXMMMMMSMAXMAMAXAXMSAMXMASXMSMXMASXSMMMSASASXAMASXMSMAMMXMAXAXXXXASXSAMSMMAMAASXMXMAMMXSSMMXAMAMMMMMMXMMMAMMAMSSSMSAAAMX
SAMMMAASMMMMMAMSSMSSSSMSSMSXMAMSAMMSSMMXAXAMASAXXAAXXMMMXAMXAMAMMAMAXAXXXSMMASMMSXMXMSMAMAMXASAMSMMAXSSMMMMMXASMMMASAAMXSAAXMAMXAMAAMASMSXXS
MAMXSSXMSMSAMXMAAMMAMXAAAXSAMXMMAMXAMXAXSSSMSSXMMSMSMAASXSSMAMAMASMMMSMMMMASASAMXAAAMAMMMAMMAMSMXMMSMAAXSAXXMASAMSMSMMSAXSXMMASXSMMSMAMAXMXS
SMMMXMAAAXSASMMSSMMAMMMMSXSXMAMSAMMAMMMMXAXXXMAMAAMXMSMSAMXMASASMXAAAMMSASMMAMAMSXXXSASXMAXMXMASXXAAMSMMSMSMSMMAMXASAMMMMXMAMMSAAMMAMXSAXAMX
AASXAMMSMXSXMAAAMXSSMMSAMASMSSXMMSSSMSXSMMMXMMAMMXMAMXAMXMAXXXASXXAMXSASXSASXSSMMMSMAASXSASMMMAMMMSSMXAAXXAMAASMMMXMAMAXAMAXSMMXMMSASMMMXSAA
SXMXXMAAMASMSMMMSAAAMASAMMMXAMASXMAXAAMXAXAASMSXSAMSSMMMSXSSSMAMMSMMXMAMAMXMAAXAXAAAMMMMMAXAAMASAAMAAMMMSSXSSMMAXMASXMMMSMMAAXMAXMSASXAAMMSS
MASMMMSXSXSAXXXXMMSSMAXAXSXMMSAMAMSMMMMXMMSMSAAAXAMAXAXAXAXAMMSMAAMMAMAMSMMMXMSMMMSXXMAXXASXSMASMSSMMSXAAXXAMXSXMAMXMAMAAAMXXMSXSMMMMXMXSXMX
XAMXSAMXAAMMXXAAXMAMMMSSMMMSAMAXAMXAXASAXAMAMMMSMXMMSSMSSMMAAXMMMSXSASAAAAMSMXMASXMXSSMSMXSAAMAXXAAXAAMMSSXMAXMMMXSMMAMSSXSMAAXXAXAXMAMSMAMM
MSXMMASAMXMAAMSMMMAMSAMXAAAMXSMMSSMXSASMMMMAMSAMXMSXMAAAAXSAMSMSAMMMXMMSSSMASMMASAMAXAMXMAMMMMSXMSMMMSASAMXMAMXAMXSASAXMMAAXMMSAMMSSSMSASAMA
XMASXMMMAMXMMXAAXMAXSXXSXMMSAMXAXAXAMMMXAAMAMMMMAMXASXSSSMSAXAAMASXSASMAAAXMSXMASAMXSAMXMMSXMAXMAMAMXAMMASXSASMXSASAMXSAMAMXMAXMXAMAMXXMMMXS
ASXMASAXSMMSMSSXMMMXMMMSXSASMSMSMMMXSAXSXSSMSAMSAMXXMAMAAASASMSMMMASASMSSMMXSAMXSAAMXMAXMXSASAMXASXMSXSXMAASAMAXMAXXMASAMMXMMXSXMXSAMSMSMSAX
MXASAMASXAAMMAAXSASAMXXSAMASASAMAASASMMMSMAAMAMSMMSXMAMAMXMXSMMXAMXMSMMAAXAXSASAXXMXAMMXMASAMXSMXSAAAMXMSMAMMMMMMSMMMXSMXSAAXMMAMXMAMMAAAMAS
SSMMXMXAMMMSMMSMSASXXSMMAMMMMMAMSMMASXXMAMMMMMMMMMAAXMASXXSASASAMXXMXMMMSMSASAMXSAXMASAAMASXSXMXAXMMMXAXXXMSASMSAXAXMAMXAXMSMXSAMAXMAMXMSMAM
XAMAMSSSXMAMAAXAMXMMMSASMMMSXMXMXAMSMAMMXXAXXAAXMASMMMAMMMMASAMXMMMSASAMXAXMMAMSAMXMAMXSMMSXMASMMXXXXMMSXSAMXXAMASXMMSSMMXMAMXMASASXSSSMMMAS
MXMAXAAMXMASXMMSMMAXAMXAAMXMASMXSAMMMSMMAMSSMSSSMXMASMAXSAMAMXMAXXAMMSASMXMXMMMXMASMASXMXXSASXMAMASXXAAXMASXMMMMMMMMAAAAAAMMSXSAMASAMXAAXSSS
MSSSMMSMXSXSAAAAMXMMMXMMMMAXXMMASAMXAAAMAXAAAAAAAXSMASXXSASAMSSXMMMSASAMMSXSASMXAMXSASAASMMMSAMSAASASMMXSAASAAXAAAXMMSSMSMSASMMXSAMMMSSMMMAM
MMAAMXXAMXAMMAMXMASASASAXSSMSAMASMSMSSSMMMSSMMSMMAMXMAMASXMXMAMMAAMMMMXMSAASAMAMSAXMSSMMMXAAXAMAMXSXSAMAMXXXMMXSSSXSAMXAAXMAMAMASAMXAAXMASAM
ASMMMXMAXMAMXXSXMASASAXXMXAASAMASAMAAAAXMAXAAAXMMMSAXAMMMSMXMASXMXMAMMMMMXMMAMAXMASMAXMSXSMSSSMAMXMASAMASXMSXSAMAMXASXMMMXSXSAMXXAMMMSSSMSAS
MMAXSXMXSSMSSXSASMMMMMMSMMMXMMMXMAMXMSMMMSSMMMMXAAMMXMXAAXMASASXASXMMASXMMSMXMMMAAMMASMXAXAAXAXAMXSASMSAXAMAASXMSMSSXMXXAAMASXSXSSMSXMAAASXM
XSMMMASAMAAAAAMAMAAXMAMXASXMAXSASMMSXMASAMAMSSSSMSXXAXXMSSMMMAMMXMAXMMXAAAMXSASMMMSAASAMXMMMSMSSSXMASAMXSSMMMMAAAAXXXSMMMSMAMAMXAASMAMSMMSAX
MMMXXAMXSMMMMMMSMMASXMMSXMAMAMXAMXAAASAMXXAMAAAXSAMSMSAMAMAMSSMSXMAMSSSSMMSASAMAASAMXXMAMXAXXXAAXMMAMAMAAXXXAMMSMMMMMAAXAXMXMAMMMMMXXMXMSXMS
AAMAMSSMMMMSXXXXAXASXSASMSMMXSMMMMASXMSMXMSMMSMMMXXAASXMAXAMXAASAXMASAAXMXMAMAMSMSMSSSXSASMAAMMSSSMSSXMMSSMSMXXAXAAAMMSMMXMAMMSMSMSSXMAXXAXX
XAMAXMAAXMASAMMSXMMSAMASAAXXAAAASXAXMAXXMAMAAMAMSMMMMMXSSSXSSMMMAMASXMXMSMMSSSMXASXAAXAMASMXMMAAXAAAAAXAAMXAMMSMSMSMSAMASASAMXAAAAMMMSSSSMMM
SSSSSXSMMMAMMAAAAXAMXMSMXMSMMSSMSMXSMAMMMMXMMSAMXXAXAMMMXAMXMAMXAMXMXAMMAAXAAAXMAMMXSMSMAMASXSXSSMMSSSMMMSSMSAXASMXAMAMAMXSXSSMMMSMXAMMAXAAX
AAAASAAMMMSSXSASXXMXMXXAXMXAAMXMXXMSMAMXAAMSASXSMSASASAMXMMXSAMSSSXSMSMSSSMMSMMMMSAMAAXMAMXMASXMXMMMAXXAXXMXMXSAMMMSMMMSMMXMAXSASAMMSSMAXSXS
SMMAMMMSAAXMAXAMAMXASAMMMMSSMSMXXMAXMSMXMXXMASASAMASXMXMASAAMXXSAMXXXAAAAAXAAAAAAAXAMMMASMXMXMMSAAAMMMSMMXMXAAMMMXAAXMAMASMMAMMXSASAAAMMMMSM
XXMXSXAXMMXSAMMMAXSAMAAMAMMAAAAXSXMMAMASXSMMAMAMSMAMAMSSMSAMMMMMMXMAXMMMXMMSSSMMSSMMSXSAMMAMASASXMXMXMAMMSSMSAMXAMMSXSAMSMAMSSSXMXMMSXMMAXMX
MXSASMMMSAAMXXXSXMMSSXMASXSAMMMMMAMSAMXMAAXSXMXMXMASMXXAMXAXXAAAMASMSSXSAMXXXMXXMXXXSAMASMASAMXXMSSSMSXSAAAMAAXMASMAAMXMMSSMAAAAXSMMAXMSMSSS
SAMXXAXAMMXMXAMXXXAAMMMMAMXAXMXAMXMMAMAMSMMXMMASASMSXMSAMSXMSSSMSASAAAAXXMXMASXXMAMXMAMXMXASXSMSMAAAAAAMMSMMSMMMAAMMMMMAMAXMMSMSMSAMAMXAAAAX
MASMSSMMSSMMSMSAMMMSSSSSSMSMMMSSSSXSAMXMMXMAAXAMXSXMAMSMMXAMMAAAMXMMMMMMXSASXMSAMSMXSMMXSMMSAMXAMMMMMMSMMAXMAAMSAMXMXAAXMAXSMMAAASAMAMMMMMSM
MASXAAXXAAAMAAAAMAXXAXAAXMAXAMXAXAASXSSXXASMSMMSMXMMSMMSMSSMMMMMSXSSXXMAMMAMAMSXMASAAAMMMSXSMMSMSXXXAMXXSXSSSXMMMMAMXMSXMAXXAMSMMXXMXMAXAAXA
MASMXSMMMSMMMMMMXXSMMMMMMSXSSSMXMMMXMAXASMMAAAAAMXXAAAXXMAMMAASASAAAXXASMMSMMXSXMAMSSMMSAXMXAASAMASAAMSAMXXXMAAXAXASASAMMSMSAMMXXXXMASMSMSSM
MASXAXAMAXAMXMMMMMMXAAXAAXMAMAMXXXMASAMMMAAMMASMMSMASMMMMSSMSXMASMMMMMXMXAMAXXMAAAMXXAAMASMMMMSAMAMSSMMAXMXASXMSSSXSMMASMAMMAMXAXSMMMAMAMXAX
SAMXXSAMASAMMMSAAXMASASMSXMMSMMMSMMAMAMXSXMXXXMXAASAAMSAXAAXXXMMMXAAAAAMMMSXMASXMMSASMMMMAAXAAXXMXMAXAMSAMMMAAMAXXMMXMSMMASXMMMMMSAAMASAMSAM
XAMAMMAMMMAMXASXSMXAXMSXXASAMAASAMMSMXMAXXMSXXAMMMSSMAXXMSSMSSSMMSSSSMXMAMAXSXMXAXMMMMSSSMXSMSMXMAMASXMXAXAMXAMASMXMAXMASXSAXSASASXMSMSMAMMM
SSSMMMSMSXSAMXMMXMMASAMASXMAMXMXASXAASMMSAASMMXMMAMAXMSSMAXAAXAXXXAAAXAASMMMMAXMMMMMMAAXAXAXAAXAMMSMXMASMSMSMSSXSAASMSSMMSMMMSAMASMAAAMAMXSX
AMAAMSMAMMMMSSMMAMMMMAMAMMSSMSMSMMMMXSAMXMXXXXAAMSSMMXAXSAMMMSMMAMSMMAMXMASXXMSXMAXAMXSSMMSSSMSSXXAMAXMMAMASAAXAXXXSXAAMSXSAAMAMMMASMSSSXMAS
MSSMMAMAMAXAAAAMXSASMXMASMAMAAAAXAXXAMAMXXMAXMXMXMAXSMMMSXSXXAXMMMAAXMXMSXMAAXMASMSMMAMAAAAXAAAAMSASXSMMXMAMMMMXMXXMMSMMAASMXXAMXAXXAAAAXSSX
XAMXXXXAMSMMSSXMMSASXXXXXMASMMSMSSSMXSAMMAAXSMSXMMMMAAXXXAMASXSAXSMSMXAAXSXSMMSAMXAAMSSSMMSMMMMSMMMMASAAAMXSAAMMMMMMMMAAMMMAMSMSSSSMMMMSAMXS
MMSMSSSMSAAMAXAMXMMMMMMMAMASAAXAAAMAMSMSXSSXAAAASAMXSMMMMSMXMASMXMXMAXMXAMMASAAAMSSSMAAASXMMSAAMMAAMXMASXSASXMSAMAAAMXXMSAMAMAAAAASXMXAMMSAX
AXMAAAAMSMSMSSSMSASAAAXAAMSSMMMMMSMAMMAMAMMXMMMXMASAMAAXAAMAMXMXAMSSSSXMAMSAMXXAMAAXMMSMMSXASMSSSXMMAXXMAAMMMXXAMMSMSAXMSASXMMSMMMMMMMXSXMAS
SMMMMSAMMAXAAAAAXASXSSMSXSAMXSAAAAMMXSAMAMSAMASMSMMMSSMSSSMMSASXSAAAMAASAMMASMSSMMSMXXMMAMMMMMMMAASXMMAMXMMSSMSSMMXMAXSASAMMXXAMXMASAMMMAMMM
MXSAMMXSMMMMMMMMMXMAXAMXMMMMMMMXSMMXAXASXMMASASAAMAAMAAXXMASMXMAMMMSMSMMAMSXSAAAXXAAMMAMSSXAAXAMMMMASXAMASAMXAAAMMAXAAMAMXAMMSASXMASASASASAS
SASMSXAMASAMAXAAMMMMSMMXMAAAAXXMMXSXASMMXSSMMMMXMSMMMMXMMMXMAAMSMXAMXMAXAXMAMMMSASXSXSAMAMMASXMSMMMAMSMMMMMXMMMSSSSMMSMXMMXSXSMMXMMSXMASASAS
MAMAMMMSASASMXSAMXAAAAAMSSSSSXSAAAMMMMAAAMMMASMXMMMSAMXMXMAMSMSAXMMSAMSSSSMAMAXMASAAASAMAMXMAMXAAAMXMAXAXAAAMAAAXMAAXAAAXXAMAXXAAMASAMAMAMAM
MAMAMAMMMSMMMMAMXMMMXSMAXMAAAASMMASAXSMMMSMSASAMXAASAMXMSSXXAXXMAXXMASXAAMMMXMSMXMMMMMMSSSSXSMSXMMMXSMSSMMSXSAMXSSSMMSSMMMAMAXMSMSASXMSMSMSM
SMSSSMSAMMMAXSSSSMXSXXXMAMMMMMMMSAXAMMAAAXXMASASMMMSAXAMMAMSXMAMSMSSMMMMMMAXASAMXXMMXSAAXXMAXASMSXXMAMAMAMXMAMMXAXAMXMMAXXSMMXXAAMMMAAMAMAAA
AAAXAXSAMAMMXMAAAXAXMAMSSMMMXMMMMXXSASXMMSAMXSXMAAXSXSSSMAMMMSMAAAMMMAXXASMSMXASMMSMAMMMMMAMMAMASAASAMASMMXMAMMXMSAMXSMXMAMAASXSSMMSMMMAMSMS
MMMSMMSXMSSMAMMMMMMSMMMXAAAXAAAASMXMASAAMXASAMXSSMXXMAXXXASAMAMSMMMXSAMMXMMAXSMMMAAMMSMSASAXMSMAMXMMASAMXAASASXAXAAMMSAAMAMMMSAAXXAAAXSMMMAM
MSAMXASAMXAMSMSAXAAAAAXSMMMSASMXSAAMASMMMXAMXSAMASXMXSXMMXSMSXXMMMSAMXSMAXSAMMAAMSSSXAAMMMSMSXMSSMMSAMXSMSXSAXMASMSMAXMXMXSXSMMMMMSSSMXSAMXM
XAAAMMXMMSXMXASASMXSSMMAAXXAXXXAMXMMXMMXSAMXMAXSAMXMMMAASMSAMMMAAXMASAAMAMMASXSXMMXMMMSMSAMXAXSAAAAMXSASMMAMAMXXAMXMXSMXSAMXMAMXSXMAMMAMMSAM
SSSMAMXSASASMMMXXXAXMMMSMMSMMSMAMAXXXAAAMAXSAXMMMMASAMXMSAXAXSSMMMSAMMAMXMXXAAMMMMAAMAMAMXSMMSMSSMMSAMMSAMXMXMMSSMXMASXAMASAMAMAXAMMMMSXXSXS
AAAXXXXMASMSAMMXSAMXAAAAAAXAAXMASXMASMMSSSMMMXMAAMAXASXXMMMSMXAASXMXSAMXMSMSMAMAASMSSMMMMSXASMAAMAAMXMASXMMXMXMAMAAMASMAXXXMXSMMSMMXAAASAMXM
MMMMSSMMMMXSAMSMSMXMSMXXMMMMMSSXSASXMMXMAXMASAXMSSSSSMMMMASXSXSMMAMXMMMAMAAAXASXMMAMXAAAMASMMMMMSSMSASMSAXMASAMAMMMMASXSASXSAXXXAMMXMMSAXMAS
XSXAAAXXMXAMAMSAXAAAXSSSSSMMSAXAMAMAAAAMMMSAMXSAAAAMMAAMSXSAMMMXXAMAXXXSSMSMSXSMSMAMSSMXSAMXASXMXMASASXMMSSSSXSAMASXMMMMMMAMASMSASAAMXMASXAA
AMMMSSMAXMMSSMMXMMMXMAXAAXASMSMMMSSSMMMXSAMAAAAMMMMMMMMXSAMXMAMASASXSXXMAMXXMXMAMSSMAAAXMASMXMASAMXMXMAXXAXAXMSAMMXAXXAXAMXMXMASMMMMSAMASMXM
MXSAMAXMXAMAXASXSXSXMMMMMMMMAMSXXAAMXMSAMASXMAXMAXAAXAXMSAMXMXSAXXAXAXSXXMSXSAMXMAXMMMMMSAMMMSMMMMXAMXSMMSMMMXSMMSSMMSSSSSXMMMMMMSAMXMMASAMS
SAMASAMMSMMMSMMAXAMAXXXAXMXMXMAMMMMMAXMASAMMMAMSMSMSSXSAMAMMXXMMSASMMMSAAAAASMSSMSSMSMSXMASAAAMASXMAXMAMAAAASXSMAAAAMAMAAXXAAAAAXSXMASMXMMAA
MAXMMMSAXAAAMMMSMMSSMMSSSMASASAXSXSXXMSAMMSMXAXAASAAAMMAMAXMMAAMAXXSAAMSMMMXMAMMAMXAAASXMASMSXSAXSAAASAMMMMMSAXMMSMMMXMSMMMSSSMSMMMAMXMAXMSM
XAMSAMXAMSMMSMAXAMAXAAAAAMASAXXMSASXAAXMXMAMMMSMSMMMSMXASXSMMASMMMAXXSMMMXMAMAMMXMASMSXAMAXMMXMMSSMMMSASXSSMMMMMXAMSXMAAAXXAMMXXMXXAMXMSXAXX
MMXSASMMMXAAAMXSSMAXMMSSMMMMMMAMMAMMMMMMASASAAXMAMAAXMSAXAAMAAMAXXAMXXMXMAXSSMSMAMXXXMXXMSSSMMSMAXAMASMMAMSAAXAXMASXASXSSMMAXXXMAMSASXAXMXMX
ASAMMAAASXMSSSMMMMSSSMXMXXSASMSMMXMXMXXSASASMAMSASMXSASASXXMMSSSMMAMSASXSXSAMMAMAXAAAXSXMAAAXSAMSSSMASAMMMMMMSMSSXMMMMAAXASAMSMXAMXSSMMSAXAM
SMASMMSMAAMAMXAMAMXAMSAMXMMASXMASMMSXAMMXMAMAXXMXSMXAMMAMXAXMXAXAXAMMAMAAXMAMSASMSSXSAMXMMSMMSASMAAMAMMSXSXMMAMAXAMXAMXMXXMAMSAMXSXXXAAXAMMA
XSAMXAXXSSMMMSMMMMMMMSXMASMAMASAMMAMAMMSSMMMXMMSAMXSMXMSMSMMSMMMXMAMMSMMMMSAMMASAMXMMMMSMAMXASMMMSMMSSXSASXXSAMASMSSMMASXXXXMMSMAXMAXMMSMSXS
AMMMMMSAMXAAAAMMMSAMXMASMSMSSMMMMMAMXXAAXAXMASAMMXAMXAAMAMXAXAMAMSAMAXAAAMMAMMAMMAAXXAAMMSSMXSAAXMXMXMAMAMAXSAMXXXAMXSASMMSAMAAMXSMSMMMAAXMM
XMASMAMMMSSMMMSAAMSXXAMXXMAMAAMASXMMMMSXSSMXXMSSXMXSSXSMMMMMSSMSASASASXMXMSSMMSMXMMXSMMSAMAMXSXMMSAMXMAMAMSMMAMAMMMSMMAXAMXAMSSMMMAAAASMSMAA
MSAMXSAMAXXAMAMMXMMSAMXMAMASMMMAAAAAXAMXMASAMXAXMASXXSXMASAMAXAXMSAMXSMXXMAMAAXMMMXMAMXMXSAMXMAMAXXXAXMMSXXASMMXSAAAXMSMXMSXMXMAAMMMSMXAMXXM
MMSSXMAMMSSSMXSAXSAMXSAMASXSMAMMSSMSMSSXSAMXMMMSXSXMMMSSXSMSASXMXMXMMMXMAMASMMSSMASMSMSAASXMASAMXSMMSXSAMXMMAMAAXMXSMXAAMMAAXAMSXMAMAXSMMSMS
SAAMMSAMAXAXSXMXXMASASAMAMAXXAMMMMAAXXAAMAMAASMMMMAMAAXXXMASAMXMXMMMAMAMXSASAAAAMSMAXAAMXSMSXSASXAAAAAMXMAXXAXMMMSAMXAMXAMSMMMXAXMXSAXMXMAAM
MMXSXSAMXMMMMMMMMSMMMSAMSSMSXSMSAMSMSMMMMASAMXAMAMXMAMMXXMAMAXXXAAAXAXXMAMMSMMSXMAMMMMMSAMAMASAMXSMMSSXMMSSSSMSAAAASAMXASXXAAMAMMMAMMMMAMMSM
SAXSXMXSAMAAAAMAAAAMXXAMXXXSMMAMXMAMXXMASXSAMXXMAXMXMSMXXMXSAMSSMSXSASMASMMXXXMXSSSXAXAXAXSMMMMSMMMXAAXMAMXAMAMMSSMMMMSSMMXMMSASAMAMSASXSMXX
MXSXAMAMMSSSSXSMSSSMXSSMSMXSAMAMAMAMSMMXXXMXMASMSMSAAAMMXSAMASXAAMMMMAMXMAMASMMMXAMAMMMSMMXXXXAAAASMSSSMASMMMSMAMMMXAAXAAAMSASAMXSAMMASAAXAX
MMSXMMASXMMAMMAAAXAMAXAAAXAXXMAXMSMMMASXMMSMMMSAAASMMMASAMASXXXSMXXMSSMASAMAXAASXMMSAAMAMAMSMMSXSMSAMAMMAMXMAXMSSMXMMXSMMMSMAMAMMMMSSMMXMMSX
XAXAXXXSAAMAMXXMXSMMSSMMMMSSSSSSXAMASAMASAAASXMXMMMXASXMASAMXMXXAMSXMASXXAMXSSMSAXAAMXSAMMAAAAXXXMMAMAMMMMAMMXAMAMSMSXXAAXXMXMAMAAAXAAAXXXMM
MSSXMASXXMMASXSAMXMAMMAAXXXAXAXXXMSMMASXMMMXMAAMXASMMMAMAXAXXMAMXMMASXMMXSAMXMAXMMMXXMSMSMSSMMSXMAMXMASAXSASMMMMMMSAMASXMMSSSMSSMXMASMMSSMSA
AXAAXXXMAXSASMAMSAMXSSSMMMMXMXMMAMAXMAMAAAMSMMMMSMSMMSAMSMMSMMAXAAMAMAMAAMAXSMXMXAXASMSAXAXXXXMAMSSMSXMAXXXAMXMASAMAMAMAAAXAAAAMXAMAXAXXMAXS
SMSAMXMASMMMMXAMMXXAMMMAAASMMSASMSXSMMMSMMXAAAXXAAXAASXMMAAAASASMXMMMAMMASMMMXMASXXXMAMMMSAMMMSMMAAXSAXSASXSAMXXMMSMMXSSMSMSMMMSSSSMSSMMMSMX
MMAMXSMAMAAXXMXSASMMSAXSMSAAASAMAXAMXMMXXMMSSMXSMXMMMSXMXMMSXMMSAASMSXSMAAMAXMAXXXASMSMXMMAAAAAXMMMMMXMAAAAXXSMXXMAMXMMXAXAXAMXXAMAMXAXXAMMM
MXMSSSXAMSMMAMMSAMXXMXXMMMMMMMAMAMXMXSAMASAXAMXXMSXSAMAXSAAMASAMXMAAXAXMMSSMMMMXMMXMAXAMXSSMMSMSMSAXXASMSMAMAAXMMSMSAASMAMSMASAMXXXMSMXMMSAA
SAMXAMSSXMSMAXAMMMSXMSXSAXAAXSSMMXSAMMAMAMXSMMAAAAXMAXMMAMXSXMSAMXMAMXMXAAAAAXSAMAAMSMSSMMAMMAAAAAAMSMMXMMAMSMAAAMXSMSXAAXASAMMSSXMAXXMXAMAX
SASMXMAXAASMMSSMSAMAMAAAMXSMMAAAAAMAMSSMMSAMXSSXMMXSMMSSMMMMXXXMASXSMAMMMSMMMXMASXXXAMXAXMAMSMSMSMSMSAMAXSXMASAMXXASXMMSMSMSXMMAXAMAXMAMSSSX
SAMXAMASXMMAMXMAMMXAMMMMXAMXMSSMMXSSMAAAAMASXMMSAXXXMAAAXXAXXAMMMMMXSAXAAMXSMSSMMMSASXMXMXMXMXAXXXAASMMMXMAMXAMXSAMSAXAAMMAMXSMSSXMASASXXAXM
MMMSMXAAAMSAMMMAMSMSSSMMMMSAXAMXMXSAMSSMMSSMMAASXXAAMMSSMSXSMXMXAAMMSXSXSMASAXXAAASAMXMSSXMAMXMASMMMMXXMAXXMMXSAXAMSMMSSMMAMXAAAAAXAXMMXMMMA
AMAMAMSSMMAMMXSSXSAXAMXAAAXMMASMMMSAMAAAAXAASMMSSMSSMAXAAXAXXASMSMSASMSAAMAMMMSSMMXAXXMAMMSMSAMAMASXMAXSSMMSMAMXSMMXXAXMASMSMMMMXSMSSMMAMMAX
XMAMXXMAAXXXMAMMAMXMASXMSSSMSASAAASXMSSMMSMMMMMXMXAMMXSMXMMMMXSAAXMXXAMXMMXXAMAMXXMSMSMAXMAASAMAXSMMMSXMAASXMASMMAASASMSMMAAAXASXMAMAASXSSMS
MSSMMASMMMMMMAXMMMSXXMAMAAAAMASMSMSMMXAMAXXAXMSAMMMSSMMMAAAXXXMXMMSMMSMSMMAMMMMSSXMMAASMMMMXSXMSXXMSAMAMSMMASXSAMXMSAMAAMSSMSMAMXSSMSMMAAAMX
XAAASMMXAAASMSSMAAMAMSSMMSMMMXMAMAMAXXAMMSSXSAMASAAAMAASXSMSSMMAXAAAMXAAAMSSMAAAMAMMXMSXMSXASMMMAMAMASMMMASXMASMMXXMAMSXMAAXXMXSMXAAXXXMSMMM
MMSMMAMSMSMSAXAXMSSMMAXAXXMXSAMAMAMSAXMMMXAMXASXMMMSSSMSXXMAAMSMMSSSMMMMMMAAMMMMXAMAMSMMMSMMMAAMMMAMASXMMAMASXSAXXASXMXMMSSMXMXMAXMMMXXXMAXX
MAXAXXMAAMXSMSMMMXXMXXXMMMSASASXSMXMMASAMXMASMMMMAMXXMASMSMXSXXXAXXAAMXAMXSMMXAXSMSASAAAXXSMXSMMAMXSXMAXMAMXMASAASMMMAMXAAMMSSMMMMAAXXXASMMS
MSSMMSMMSMAMMAAAXXXMASASXMMASAMASMXSXMSASASXXMMASAMXAMXMAAXSAXMMSMMSMMSSSMXSASXXAASXMMSMSSXSAAMSSSMSMSXMMMSMSXMMMSAASXSMMMSAAAAAXSSMSSMMMAAM
XMAXAAASAMMSMSXMMMASASAMXAMAMAMAMXXMAMMMMAMMAMXMXMSSMMAMSMSXAAMMASXMMAXAAAMSXAXSMXMASAXXXXAMSSMAMAAMASMSMAAAXXAXASAMAAAMSSMMSSMMXMAMAXAASMMX
XSAMXSMSASAAAMSMXSAMXSXMXSMSSSMXXAMSXMASMAMSSMSXSAMXAAAMAXXMMMXSAXMAMXSSMMMSXMASXAMXAASMMMMMMXMMSMMMMMAAMMMSMMXMASMSMAMXMASAXAAXAXAMXSMXSXSX
MMMSAMASXMMSXSAMXMASXMMSAXXMAXAMMMAAASASMSMMXAAAAXXSMSMSMSMAMSAMXXSAMXMXAMAXAXMMMXMAMSMAAAAAXMXMXXXAMMSMSMMXMMAMXMAXXXMASMMMSSMMMSXSASXMMAXS
MAASASAMAMAMMSAMXXAMXAAMASAMMMMMAMXSMMASMMAMMMMSMMAXAAAAAAMAMMASAXMASXMASMMSASASMSMAXAXSMXXMMXMMMMSMSAMMAASXMSMXAMSMMMSASXAMXMASXAXMAMASMMMX
SMMSMMAXXMAXAMMXSMMSSMMSXXAMXASXMSAXMSXSASMMAXXMASXMSMSMSMSSMSAMXSSMMAXAMXXAASAMAAXAMSXMASXSSMSMAAAXMASMSSMAAXAASXMAMAMASMXXXMAXSSXXAMAMAXAA
ASAMXSXMMSMSMAMAMXAAAXXXXSXMSXSAAMAMAMASAMXSSSXSAMMXMAAXAMXMMMMSMXAASXMMMMSMMMXMSMMXAMAMAMAASAAMSSMMMAMXMAXMMMMMMASXMAMAMMSXXMSXXMAMSSXSMMSA
AMMXMASAAAXAXAMMSSMSSMMSMSMASAMMMMAMXMAMAMMAMXAMAMXAMSMXMMXMXAMAMXMMMXAMAAXXXAXAAAXSXMAMAMMMMSMXMAMSSMMASMMMXAXASXMXSASAAXAMXAXSMXSAMXASXMAM
SXMMSXAMSSSSSXSAMAAAMXAAAMMAMAMMSSSSSMMSAMMSAMXSAMSAXMAMXMAMXMSASXMSSMSSMSMSXMMSMAMSASMSSSMMMMXAMAMMAMSASAAXMXMAXAAAXASMSMMAASMXMAXAAMAMAXMM
XAMAMXMAXXMAMMMASMMMSSSMSMMXSXMMMAAMXAASAMAMXMXSAMMMAMXAAMASAAMASAAAAAAAAAXSASMAMAAXAMAAAAXMASMSSSMMAMMXSMMXAAAMSMMAMXMAMAXSSMXAMXSASMAXSMMX
SMMASMXMXXMMMASAMXSAAAXAMXMXSXSAMMMMSMMSXMASAAMSXMMSAMMSXSASMSMASMMMXSMMMMMSAMSXMXSMSMMMSSMMASAXAAASMMSXMAXMSXMXAXSXSMMXMXMMAMSXSAMMXMSAMASM
AXMAXAAMSMSXSASXSXAMMSMMMASMSASXMSAXXMASASASMSAMAMAMASXMXMAXMXMASXASAXMSXMAMXMAXMSXMMAMAMAMAXMXMMMMMSAMXSMMAXXSMMMAAAAXMASMSAMMAMXMSAAXMSXMA
MSMSXXAMAAMAMASAMMMMAXAAXXSAMXMAMSASMXASAMASAXMXAMMXXMXMMMMSSMMXXMASMSAAAMSMXMAXSAAMXSMMXAMAMXMXSAXXMXMAAXAMSAMASXMXMSMMAXASXMMASMAMMSSXMASM
XXAMASXSMXMAMMMMMAXMSSMMSSMXMMXMXXXMMMXSMMMMMMSSMSXAXSAMXAXXAASXSMAMXMMMSMMAXAMXXAXMAXAXSAMSAMXAXXSXMASXMASXMAMAMAXSSMXASMMMAXSAMXXXSMMAXAMA
SMAMAMAAXASXSAAASMSMMAASXMAAXAAMMMMSXSMXXAXAXMXAMSMMSAAMSMSSSMMAXMAMXMMXXAMMMMMMMSMMXSAMSXMASAMMSMAMAMXSMXXAMAMAXXMMAAMMXAAMAMMASXXXMAMSMXSM
AAAMAMMMMMXAMMXMSXMASXMSAMSMSSMSAAXAAXMASMMSXXSAMXAMAXMMMAMAXMMMMSMSSMSXMAMAAXXAAAAXAMAMXASAMMMMAXXSXMAAMAMASMSMSMMSMMMXSMMMSSSXMXMMMSMAXMAX
SSMSXXAAAXMMMSSMMXSAMXAXXMAMAMASXSMMSMMXMMMXMMSMMMXMAXXXMAMXMMXMAMMAAMAASXMSMSAMSMMMXMASMXMASASMMMASAMXAMXSAMMAXAMXXAXXXMMAXMXMXAMXSAMXAMMXM
MAMXASMMMXMMAAAMAMMASMMMSSMMAMMMXXAMXAXAXAASAAXAXAXMMSSMMMSMAXAMXSMSSMSXMAXAMXAMAXMSMSASAMXAMXMAASMSXMSXMXMASXSSMSSSMMXMASMMSAMMXMAXASMSSSMM
SAMMXMAASAMXMSXMAMSAMXAAXASMMMXMAXASMSMAMMSSMMXXMMAXAAMAAAAAMSMSXAAAMMXSAMXAXXAMXSMAAMAXMAMXSAMMMMAXAMXAAXSSMAXAXAAAXAXMAMXAMAMASMXMAMAAAMAX
SAMXXXMASAXMXXASAXXMASMMSMMMSSSMMSAMAMAXMSAMASXMMSSMMSSSMMSSXAAMXMMMSXSAMXSSMSSMAXMMMMXMXMSASXXMAAMSAMMSAMXXMSSMMSMMMSXMASMSSSMAMAXMMMMMSMMM
XAXSAMXMSXMSASAMXSAMAXAAXXAAMXAAAMXMAMXXXXASAMXAXAAAMAMXSXAXXMMXAMXMAMXMAMXXAAAMXSSXMXAMAXMXSAXSAMXMAXAXASMSAMXXAXASXMAMXMAXXASXMSAMXAAAAAXA
MSMMASXMSMXMASAMXXAMXMMMXSMSSXMMXMMSASMMMSXMAXMSMSSMMMSAMMMMXSASXSSMSMSXMXXMMMSAMXXAMSASMXMXMXMAAMASMMXSMAAMASAMSSMSASMMSMMMMMAXAXASASMMXSXX
MXAXAMAMMSAMXMASXSSMMSASAXMAMXSXMMAMAMAAAXMXSXAAAXAXAAMASMXSXMASAAAAAAMXXMMXAAAAMASMMMASAASXMMASMMMAAMXMMAXMASAMXXASAMMAAAAAAXMMAMAMAAXXSMMX
SMXMXMXAASMSAMXSXSAAXSAMXSMSMXSASMASASXMXSXAMMSMSMMSMXSAMAASAMXMMMMSMSMMAMXAMMSAMASXXXAMXMSAMAMMXXMXAMXMMSSMXSAMMMMMAXMXSSMMXXXMASAMXMAXAAXX
AASXMAMXMSASMMAXMXMMMMMMMMAAAAMAMMAXXSXMSMMASAMAAAXAAXMMSMAMXSAAAXXMXMMSASXSSXMAMSSXXMASAMSAMSMSMMXSMSXSAAAXAMAAXAXMAMSMMMMSMMXSASMXMXMSMSMX
MSMAASMSMMAMAMASAAXXXAAAMMSMSXMMMMMXMSAMAASAMMSSSSMMSMMAXXAMXSXSMSAMAXXSMMMAMXXAMXMXMSAXXMXAMMAAAMMAMXAMMSSMSSXMSXXMSMMAMMAAAAXMASXXAAXAMXAX
XAMXMMAXSMXSMMXAXMSMSMSXSXAAAASAMXMAMXASXMMASAAMAAXAMAMSSSMSAMXXASMMASAMXMMSMMSMSXMAMMSSSSSMMMSMSMAAXMXMXXMAXAXXXXXXMASMMMSSXMXMASMSSSSMMMSX
MMAXMMXMXSAMXMXMXMAAMAMASMMSMXSASASMSMMMMXSXMMSSSXMXSSMMAMXMMSASMMSMAMASXASAMAAAAXSAMSAXMAXAAAXXMMSMMSSMMSSSMSMSASMXSAMASXAXAMXMXMAXAXAAAAMM
AXSAMAXMMMMSAMMXASMMSAMAMAXAMMSAMASAAXSSSMXAMXMAMMSMAAXMXMXXXMMSAMXMSSXMMMSASMMSSXSXSAMXMAMMMMMXXAAAXXAAAAAAAXAMXMAASASAMMAXMXMASMSMMMSMMMSA
SMAASXSMAAASMMAMXSAAMAMMMXMMXAMXMMMXMASAAXSSMSXAAASASMMSSSMMSAMXMMXXXXAMAXSAMXMAMAMMSMXXMSXSASAAMSSSMSSMMMSMMMSMXMMMSXMAMMMMSAXAXMXMAAXAMAMX
XAMXMAAASXXSASMSAMMMSXSMMXMXMMMMSAMXXSXSMMSAAMXMMASAMXXAAAXXAAASMSXXMSMMSMMMSMMMSXMASXXXMAAMAMMSMAAAMAMAMMMAXXAXSXMMMMSSXXMASASXSMASMSSXMAMX
MSSMMSMMMMXSAMAMAXAAAASAAASASMSASASMMMAMXXXMMMXMMXMAMAMMSMMSSSMSAMXXMAMAXMAXMAXMXMMXSMSSMMSMAMAXMMSMMASMMAMSMSMSXMSAAMAMMSSMMXMAAMAXMMMMSMSM
AXAAAMASXXAMAMXMXAMSMXMMSXSASAAXSXXAAXAMSAMXAAAXAASMMAAXMAXAAAAMMMXMMAMASMSMSAMSAMXAMXAMAAXMXMASXAXXSMSASASAAAMXXASMSMMSAAAXSAMSMMSXSAAAAAAA
XSSMMSAMXMXSXMASXXXXXMAXXMMXMMMAXMSSMSASXSASXSSSSMXSSSSMSSMMSMMMAXMASXSMSAMXMXMSAXMASMSSMMSAMXXXMSMMAMXMSSSMSMSMXXMSXMXMMSSMSMMMSAMXSSSSMSMS";

$sample = "MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX";
//140 x 140

//      N
//      ^
// W <- + -> E
//      v
//      S

$xmasCount = 0;

//prep array of arrayed characters 140 x 140
foreach(explode("\n", $input) as $row) {
    $wordArray[] = str_split($row);
}

function xmasCheck(array $input): bool
{
    $word = implode($input);

    return $word == 'XMAS';
}

function checkForXmas(
    array $data,
    array $coords,
    bool $north = false,
    bool $northEast = false,
    bool $east = false,
    bool $southEast = false,
    bool $south = false,
    bool $southWest = false,
    bool $west = false,
    bool $northWest = false,
): int {
    [$x, $y] = $coords;
    $count = 0;
    $word = [];

    if ($north) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y - $i][$x];
        }

        if (xmasCheck($word)) {
            $count++;
        }

        $word = [];
    }

    if ($northEast) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y - $i][$x + $i];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    if ($east) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y][$x + $i];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    if ($southEast) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y + $i][$x + $i];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    if ($south) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y + $i][$x];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    if ($southWest) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y + $i][$x - $i];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    if ($west) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y][$x - $i];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    if ($northWest) {
        for($i = 0; $i < 4; $i++) {
            $word[] = $data[$y - $i][$x - $i];
        }

        if (xmasCheck($word)) {
            $count++;
        };

        $word = [];
    }

    return $count;
}
//
////if row less than 3 we cannot check toward North
////if row more than 136 we cannot check toward South
////if column less than 3 we cannot check towards West
////if column more than 136 we cannot check towards East
//
////no NW check if row and col is less than 3
////no SE check if row and col is more than 136
////no SW check if col is less than 3 and row is more than 136
////no NE check if col is more than 136 and row is less than 3
//$max = 6;
$min = 3;
$max = 136;
foreach($wordArray as $row => $rowData) {
    $xLocationsToCheck = array_keys($rowData, 'X');
    foreach($xLocationsToCheck as $xLocation) {
        if ($row < $min) {
            if ($xLocation < $min) {
               //cannot check to SW, W, NW, N, NE
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    east: true,
                    southEast: true,
                    south: true,
                );
            } elseif ($xLocation > $max) {
                //cannot check to NW, N, NE, E, SE
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    south: true,
                    southWest: true,
                    west: true
                );
            } else {
                // cannot check NW, N, NE
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    east: true,
                    southEast: true,
                    south: true,
                    southWest: true,
                    west: true
                );
            }
        } elseif ($row > $max) {
            if ($xLocation < $min) {
                //cannot check to SE, S, SW, W, NW
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    north: true,
                    northEast: true,
                    east: true,
                );
            } elseif ($xLocation > $max) {
                //cannot check to NE, E, SE, S, SW
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    north: true,
                    west: true,
                    northWest: true
                );
            } else {
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    north: true,
                    northEast: true,
                    east: true,
                    west: true,
                    northWest: true
                );
            }
        } else {
            if ($xLocation < $min) {
                //cannot check to W, SW and NW
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    north: true,
                    northEast: true,
                    east: true,
                    southEast: true,
                    south: true
                );
            } elseif ($xLocation > $max) {
                //cannot check to E, SE and NE
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    north: true,
                    south: true,
                    southWest: true,
                    west: true,
                    northWest: true
                );
            } else {
                $xmasCount += checkForXmas(
                    $wordArray,
                    [$xLocation, $row],
                    north: true,
                    northEast: true,
                    east: true,
                    southEast: true,
                    south: true,
                    southWest: true,
                    west: true,
                    northWest: true,
                );
            }
        }
    }
 }

echo "$xmasCount \n";